server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payBuddy
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/